<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('rule_bb_pb_women')->insert([
            ['length_cm' => '55.5', 'minus_three_sd' => '3.6', 'minus_two_sd' => '3.9', 'minus_one_sd' => '4.3', 'median' => '4.7', 'plus_one_sd' => '5.1', 'plus_two_sd' => '5.7', 'plus_three_sd' => '6.3'],
            ['length_cm' => '56.0', 'minus_three_sd' => '3.7', 'minus_two_sd' => '4.0', 'minus_one_sd' => '4.4', 'median' => '4.8', 'plus_one_sd' => '5.3', 'plus_two_sd' => '5.8', 'plus_three_sd' => '6.4'],
            ['length_cm' => '56.5', 'minus_three_sd' => '3.8', 'minus_two_sd' => '4.1', 'minus_one_sd' => '4.5', 'median' => '5.0', 'plus_one_sd' => '5.4', 'plus_two_sd' => '6.0', 'plus_three_sd' => '6.6'],
            ['length_cm' => '57.0', 'minus_three_sd' => '3.9', 'minus_two_sd' => '4.3', 'minus_one_sd' => '4.6', 'median' => '5.1', 'plus_one_sd' => '5.6', 'plus_two_sd' => '6.1', 'plus_three_sd' => '6.8'],
            ['length_cm' => '57.5', 'minus_three_sd' => '4.0', 'minus_two_sd' => '4.4', 'minus_one_sd' => '4.8', 'median' => '5.2', 'plus_one_sd' => '5.7', 'plus_two_sd' => '6.3', 'plus_three_sd' => '7.0'],
            ['length_cm' => '58.0', 'minus_three_sd' => '4.1', 'minus_two_sd' => '4.5', 'minus_one_sd' => '4.9', 'median' => '5.4', 'plus_one_sd' => '5.9', 'plus_two_sd' => '6.5', 'plus_three_sd' => '7.1'],
            ['length_cm' => '58.5', 'minus_three_sd' => '4.2', 'minus_two_sd' => '4.6', 'minus_one_sd' => '5.0', 'median' => '5.5', 'plus_one_sd' => '6.0', 'plus_two_sd' => '6.6', 'plus_three_sd' => '7.3'],
            ['length_cm' => '59.0', 'minus_three_sd' => '4.3', 'minus_two_sd' => '4.7', 'minus_one_sd' => '5.1', 'median' => '5.6', 'plus_one_sd' => '6.2', 'plus_two_sd' => '6.8', 'plus_three_sd' => '7.5'],
            ['length_cm' => '59.5', 'minus_three_sd' => '4.4', 'minus_two_sd' => '4.8', 'minus_one_sd' => '5.3', 'median' => '5.7', 'plus_one_sd' => '6.3', 'plus_two_sd' => '6.9', 'plus_three_sd' => '7.7'],
            ['length_cm' => '60.0', 'minus_three_sd' => '4.5', 'minus_two_sd' => '4.9', 'minus_one_sd' => '5.4', 'median' => '5.9', 'plus_one_sd' => '6.4', 'plus_two_sd' => '7.1', 'plus_three_sd' => '7.8'],
            ['length_cm' => '60.5', 'minus_three_sd' => '4.6', 'minus_two_sd' => '5.0', 'minus_one_sd' => '5.5', 'median' => '6.0', 'plus_one_sd' => '6.6', 'plus_two_sd' => '7.3', 'plus_three_sd' => '8.0'],
            ['length_cm' => '61.0', 'minus_three_sd' => '4.7', 'minus_two_sd' => '5.1', 'minus_one_sd' => '5.6', 'median' => '6.1', 'plus_one_sd' => '6.7', 'plus_two_sd' => '7.4', 'plus_three_sd' => '8.2'],
            ['length_cm' => '61.5', 'minus_three_sd' => '4.8', 'minus_two_sd' => '5.2', 'minus_one_sd' => '5.7', 'median' => '6.3', 'plus_one_sd' => '6.9', 'plus_two_sd' => '7.6', 'plus_three_sd' => '8.4'],
            ['length_cm' => '62.0', 'minus_three_sd' => '4.9', 'minus_two_sd' => '5.3', 'minus_one_sd' => '5.8', 'median' => '6.4', 'plus_one_sd' => '7.0', 'plus_two_sd' => '7.7', 'plus_three_sd' => '8.5'],
            ['length_cm' => '62.5', 'minus_three_sd' => '5.0', 'minus_two_sd' => '5.4', 'minus_one_sd' => '5.9', 'median' => '6.5', 'plus_one_sd' => '7.1', 'plus_two_sd' => '7.8', 'plus_three_sd' => '8.7'],
            ['length_cm' => '63.0', 'minus_three_sd' => '5.1', 'minus_two_sd' => '5.5', 'minus_one_sd' => '6.0', 'median' => '6.6', 'plus_one_sd' => '7.3', 'plus_two_sd' => '8.0', 'plus_three_sd' => '8.8'],
            ['length_cm' => '63.5', 'minus_three_sd' => '5.2', 'minus_two_sd' => '5.6', 'minus_one_sd' => '6.2', 'median' => '6.7', 'plus_one_sd' => '7.4', 'plus_two_sd' => '8.1', 'plus_three_sd' => '9.0'],
            ['length_cm' => '64.0', 'minus_three_sd' => '5.3', 'minus_two_sd' => '5.7', 'minus_one_sd' => '6.3', 'median' => '6.9', 'plus_one_sd' => '7.5', 'plus_two_sd' => '8.3', 'plus_three_sd' => '9.1'],
            ['length_cm' => '64.5', 'minus_three_sd' => '5.4', 'minus_two_sd' => '5.8', 'minus_one_sd' => '6.4', 'median' => '7.0', 'plus_one_sd' => '7.6', 'plus_two_sd' => '8.4', 'plus_three_sd' => '9.3'],
            ['length_cm' => '65.0', 'minus_three_sd' => '5.5', 'minus_two_sd' => '5.9', 'minus_one_sd' => '6.5', 'median' => '7.1', 'plus_one_sd' => '7.8', 'plus_two_sd' => '8.6', 'plus_three_sd' => '9.5'],
            ['length_cm' => '65.5', 'minus_three_sd' => '5.5', 'minus_two_sd' => '6.0', 'minus_one_sd' => '6.6', 'median' => '7.2', 'plus_one_sd' => '7.9', 'plus_two_sd' => '8.7', 'plus_three_sd' => '9.6'],
            ['length_cm' => '66.0', 'minus_three_sd' => '5.6', 'minus_two_sd' => '6.1', 'minus_one_sd' => '6.7', 'median' => '7.3', 'plus_one_sd' => '8.0', 'plus_two_sd' => '8.8', 'plus_three_sd' => '9.8'],
            ['length_cm' => '66.5', 'minus_three_sd' => '5.7', 'minus_two_sd' => '6.2', 'minus_one_sd' => '6.8', 'median' => '7.4', 'plus_one_sd' => '8.1', 'plus_two_sd' => '9.0', 'plus_three_sd' => '9.9'],
            ['length_cm' => '67.0', 'minus_three_sd' => '5.8', 'minus_two_sd' => '6.3', 'minus_one_sd' => '6.9', 'median' => '7.5', 'plus_one_sd' => '8.3', 'plus_two_sd' => '9.1', 'plus_three_sd' => '10.0'],
            ['length_cm' => '67.5', 'minus_three_sd' => '5.9', 'minus_two_sd' => '6.4', 'minus_one_sd' => '7.0', 'median' => '7.6', 'plus_one_sd' => '8.4', 'plus_two_sd' => '9.2', 'plus_three_sd' => '10.2'],
            ['length_cm' => '68.0', 'minus_three_sd' => '6.0', 'minus_two_sd' => '6.5', 'minus_one_sd' => '7.1', 'median' => '7.7', 'plus_one_sd' => '8.5', 'plus_two_sd' => '9.4', 'plus_three_sd' => '10.3'],
            ['length_cm' => '68.5', 'minus_three_sd' => '6.1', 'minus_two_sd' => '6.6', 'minus_one_sd' => '7.2', 'median' => '7.9', 'plus_one_sd' => '8.6', 'plus_two_sd' => '9.5', 'plus_three_sd' => '10.5'],
            ['length_cm' => '69.0', 'minus_three_sd' => '6.1', 'minus_two_sd' => '6.7', 'minus_one_sd' => '7.3', 'median' => '8.0', 'plus_one_sd' => '8.7', 'plus_two_sd' => '9.6', 'plus_three_sd' => '10.6'],
            ['length_cm' => '69.5', 'minus_three_sd' => '6.2', 'minus_two_sd' => '6.8', 'minus_one_sd' => '7.4', 'median' => '8.1', 'plus_one_sd' => '8.8', 'plus_two_sd' => '9.7', 'plus_three_sd' => '10.7'],
            ['length_cm' => '70.0', 'minus_three_sd' => '6.3', 'minus_two_sd' => '6.9', 'minus_one_sd' => '7.5', 'median' => '8.2', 'plus_one_sd' => '9.0', 'plus_two_sd' => '9.9', 'plus_three_sd' => '10.9'],
            ['length_cm' => '70.5', 'minus_three_sd' => '6.4', 'minus_two_sd' => '6.9', 'minus_one_sd' => '7.6', 'median' => '8.3', 'plus_one_sd' => '9.1', 'plus_two_sd' => '10.0', 'plus_three_sd' => '11.0'],
            ['length_cm' => '71.0', 'minus_three_sd' => '6.5', 'minus_two_sd' => '7.0', 'minus_one_sd' => '7.7', 'median' => '8.4', 'plus_one_sd' => '9.2', 'plus_two_sd' => '10.1', 'plus_three_sd' => '11.1'],
            ['length_cm' => '71.5', 'minus_three_sd' => '6.5', 'minus_two_sd' => '7.1', 'minus_one_sd' => '7.7', 'median' => '8.5', 'plus_one_sd' => '9.3', 'plus_two_sd' => '10.2', 'plus_three_sd' => '11.3'],
            ['length_cm' => '72.0', 'minus_three_sd' => '6.6', 'minus_two_sd' => '7.2', 'minus_one_sd' => '7.8', 'median' => '8.6', 'plus_one_sd' => '9.4', 'plus_two_sd' => '10.3', 'plus_three_sd' => '11.4'],
            ['length_cm' => '72.5', 'minus_three_sd' => '6.7', 'minus_two_sd' => '7.3', 'minus_one_sd' => '7.9', 'median' => '8.7', 'plus_one_sd' => '9.5', 'plus_two_sd' => '10.5', 'plus_three_sd' => '11.5'],
            ['length_cm' => '73.0', 'minus_three_sd' => '6.8', 'minus_two_sd' => '7.4', 'minus_one_sd' => '8.0', 'median' => '8.8', 'plus_one_sd' => '9.6', 'plus_two_sd' => '10.6', 'plus_three_sd' => '11.7'],
            ['length_cm' => '73.5', 'minus_three_sd' => '6.9', 'minus_two_sd' => '7.4', 'minus_one_sd' => '8.1', 'median' => '8.9', 'plus_one_sd' => '9.7', 'plus_two_sd' => '10.7', 'plus_three_sd' => '11.8'],
            ['length_cm' => '74.0', 'minus_three_sd' => '6.9', 'minus_two_sd' => '7.5', 'minus_one_sd' => '8.2', 'median' => '9.0', 'plus_one_sd' => '9.8', 'plus_two_sd' => '10.8', 'plus_three_sd' => '11.9'],
            ['length_cm' => '74.5', 'minus_three_sd' => '7.0', 'minus_two_sd' => '7.6', 'minus_one_sd' => '8.3', 'median' => '9.1', 'plus_one_sd' => '9.9', 'plus_two_sd' => '10.9', 'plus_three_sd' => '12.0'],
            ['length_cm' => '75.0', 'minus_three_sd' => '7.1', 'minus_two_sd' => '7.7', 'minus_one_sd' => '8.4', 'median' => '9.1', 'plus_one_sd' => '10.0', 'plus_two_sd' => '11.0', 'plus_three_sd' => '12.2'],
            ['length_cm' => '75.5', 'minus_three_sd' => '7.1', 'minus_two_sd' => '7.8', 'minus_one_sd' => '8.5', 'median' => '9.2', 'plus_one_sd' => '10.1', 'plus_two_sd' => '11.1', 'plus_three_sd' => '12.3'],
            ['length_cm' => '76.0', 'minus_three_sd' => '7.2', 'minus_two_sd' => '7.8', 'minus_one_sd' => '8.5', 'median' => '9.3', 'plus_one_sd' => '10.2', 'plus_two_sd' => '11.2', 'plus_three_sd' => '12.4'],
            ['length_cm' => '76.5', 'minus_three_sd' => '7.3', 'minus_two_sd' => '7.9', 'minus_one_sd' => '8.6', 'median' => '9.4', 'plus_one_sd' => '10.3', 'plus_two_sd' => '11.4', 'plus_three_sd' => '12.5'],
            ['length_cm' => '77.0', 'minus_three_sd' => '7.4', 'minus_two_sd' => '8.0', 'minus_one_sd' => '8.7', 'median' => '9.5', 'plus_one_sd' => '10.4', 'plus_two_sd' => '11.5', 'plus_three_sd' => '12.6'],
            ['length_cm' => '77.5', 'minus_three_sd' => '7.4', 'minus_two_sd' => '8.1', 'minus_one_sd' => '8.8', 'median' => '9.6', 'plus_one_sd' => '10.5', 'plus_two_sd' => '11.6', 'plus_three_sd' => '12.8'],
            ['length_cm' => '78.0', 'minus_three_sd' => '7.5', 'minus_two_sd' => '8.2', 'minus_one_sd' => '8.9', 'median' => '9.7', 'plus_one_sd' => '10.6', 'plus_two_sd' => '11.7', 'plus_three_sd' => '12.9'],
            ['length_cm' => '78.5', 'minus_three_sd' => '7.6', 'minus_two_sd' => '8.2', 'minus_one_sd' => '9.0', 'median' => '9.8', 'plus_one_sd' => '10.7', 'plus_two_sd' => '11.8', 'plus_three_sd' => '13.0'],
            ['length_cm' => '79.0', 'minus_three_sd' => '7.7', 'minus_two_sd' => '8.3', 'minus_one_sd' => '9.1', 'median' => '9.9', 'plus_one_sd' => '10.8', 'plus_two_sd' => '11.9', 'plus_three_sd' => '13.1'],
            ['length_cm' => '79.5', 'minus_three_sd' => '7.7', 'minus_two_sd' => '8.4', 'minus_one_sd' => '9.1', 'median' => '10.0', 'plus_one_sd' => '10.9', 'plus_two_sd' => '12.0', 'plus_three_sd' => '13.3'],
            ['length_cm' => '80.0', 'minus_three_sd' => '7.8', 'minus_two_sd' => '8.5', 'minus_one_sd' => '9.2', 'median' => '10.1', 'plus_one_sd' => '11.0', 'plus_two_sd' => '12.1', 'plus_three_sd' => '13.4'],
            ['length_cm' => '80.5', 'minus_three_sd' => '7.9', 'minus_two_sd' => '8.6', 'minus_one_sd' => '9.3', 'median' => '10.2', 'plus_one_sd' => '11.2', 'plus_two_sd' => '12.3', 'plus_three_sd' => '13.5'],
            ['length_cm' => '81.0', 'minus_three_sd' => '8.0', 'minus_two_sd' => '8.7', 'minus_one_sd' => '9.4', 'median' => '10.3', 'plus_one_sd' => '11.3', 'plus_two_sd' => '12.4', 'plus_three_sd' => '13.7'],
            ['length_cm' => '81.5', 'minus_three_sd' => '8.1', 'minus_two_sd' => '8.8', 'minus_one_sd' => '9.5', 'median' => '10.4', 'plus_one_sd' => '11.4', 'plus_two_sd' => '12.5', 'plus_three_sd' => '13.8'],
            ['length_cm' => '82.0', 'minus_three_sd' => '8.1', 'minus_two_sd' => '8.8', 'minus_one_sd' => '9.6', 'median' => '10.5', 'plus_one_sd' => '11.5', 'plus_two_sd' => '12.6', 'plus_three_sd' => '13.9'],
            ['length_cm' => '82.5', 'minus_three_sd' => '8.2', 'minus_two_sd' => '8.9', 'minus_one_sd' => '9.7', 'median' => '10.6', 'plus_one_sd' => '11.6', 'plus_two_sd' => '12.8', 'plus_three_sd' => '14.1'],
            ['length_cm' => '83.0', 'minus_three_sd' => '8.3', 'minus_two_sd' => '9.0', 'minus_one_sd' => '9.8', 'median' => '10.7', 'plus_one_sd' => '11.8', 'plus_two_sd' => '12.9', 'plus_three_sd' => '14.2'],
            ['length_cm' => '83.5', 'minus_three_sd' => '8.4', 'minus_two_sd' => '9.1', 'minus_one_sd' => '9.9', 'median' => '10.9', 'plus_one_sd' => '11.9', 'plus_two_sd' => '13.1', 'plus_three_sd' => '14.4'],
            ['length_cm' => '84.0', 'minus_three_sd' => '8.5', 'minus_two_sd' => '9.2', 'minus_one_sd' => '10.1', 'median' => '11.0', 'plus_one_sd' => '12.0', 'plus_two_sd' => '13.2', 'plus_three_sd' => '14.5'],
            ['length_cm' => '84.5', 'minus_three_sd' => '8.6', 'minus_two_sd' => '9.3', 'minus_one_sd' => '10.2', 'median' => '11.1', 'plus_one_sd' => '12.1', 'plus_two_sd' => '13.3', 'plus_three_sd' => '14.7'],
            ['length_cm' => '85.0', 'minus_three_sd' => '8.7', 'minus_two_sd' => '9.4', 'minus_one_sd' => '10.3', 'median' => '11.2', 'plus_one_sd' => '12.3', 'plus_two_sd' => '13.5', 'plus_three_sd' => '14.9'],
            ['length_cm' => '85.5', 'minus_three_sd' => '8.8', 'minus_two_sd' => '9.5', 'minus_one_sd' => '10.4', 'median' => '11.3', 'plus_one_sd' => '12.4', 'plus_two_sd' => '13.6', 'plus_three_sd' => '15.0'],
            ['length_cm' => '86.0', 'minus_three_sd' => '8.9', 'minus_two_sd' => '9.7', 'minus_one_sd' => '10.5', 'median' => '11.5', 'plus_one_sd' => '12.6', 'plus_two_sd' => '13.8', 'plus_three_sd' => '15.2'],
            ['length_cm' => '86.5', 'minus_three_sd' => '9.0', 'minus_two_sd' => '9.8', 'minus_one_sd' => '10.6', 'median' => '11.6', 'plus_one_sd' => '12.7', 'plus_two_sd' => '13.9', 'plus_three_sd' => '15.4'],
            ['length_cm' => '87.0', 'minus_three_sd' => '9.1', 'minus_two_sd' => '9.9', 'minus_one_sd' => '10.7', 'median' => '11.7', 'plus_one_sd' => '12.8', 'plus_two_sd' => '14.1', 'plus_three_sd' => '15.5'],
            ['length_cm' => '87.5', 'minus_three_sd' => '9.2', 'minus_two_sd' => '10.0', 'minus_one_sd' => '10.9', 'median' => '11.8', 'plus_one_sd' => '13.0', 'plus_two_sd' => '14.2', 'plus_three_sd' => '15.7'],
            ['length_cm' => '88.0', 'minus_three_sd' => '9.3', 'minus_two_sd' => '10.1', 'minus_one_sd' => '11.0', 'median' => '12.0', 'plus_one_sd' => '13.1', 'plus_two_sd' => '14.4', 'plus_three_sd' => '15.9'],
            ['length_cm' => '88.5', 'minus_three_sd' => '9.4', 'minus_two_sd' => '10.2', 'minus_one_sd' => '11.1', 'median' => '12.1', 'plus_one_sd' => '13.2', 'plus_two_sd' => '14.5', 'plus_three_sd' => '16.0'],
            ['length_cm' => '89.0', 'minus_three_sd' => '9.5', 'minus_two_sd' => '10.3', 'minus_one_sd' => '11.2', 'median' => '12.2', 'plus_one_sd' => '13.4', 'plus_two_sd' => '14.7', 'plus_three_sd' => '16.2'],
            ['length_cm' => '89.5', 'minus_three_sd' => '9.6', 'minus_two_sd' => '10.4', 'minus_one_sd' => '11.3', 'median' => '12.3', 'plus_one_sd' => '13.5', 'plus_two_sd' => '14.8', 'plus_three_sd' => '16.4'],
            ['length_cm' => '90.0', 'minus_three_sd' => '9.7', 'minus_two_sd' => '10.5', 'minus_one_sd' => '11.4', 'median' => '12.5', 'plus_one_sd' => '13.7', 'plus_two_sd' => '15.0', 'plus_three_sd' => '16.5'],
            ['length_cm' => '90.5', 'minus_three_sd' => '9.8', 'minus_two_sd' => '10.6', 'minus_one_sd' => '11.5', 'median' => '12.6', 'plus_one_sd' => '13.8', 'plus_two_sd' => '15.1', 'plus_three_sd' => '16.7'],
            ['length_cm' => '91.0', 'minus_three_sd' => '9.9', 'minus_two_sd' => '10.7', 'minus_one_sd' => '11.7', 'median' => '12.7', 'plus_one_sd' => '13.9', 'plus_two_sd' => '15.3', 'plus_three_sd' => '16.9'],
            ['length_cm' => '91.5', 'minus_three_sd' => '10.0', 'minus_two_sd' => '10.8', 'minus_one_sd' => '11.8', 'median' => '12.8', 'plus_one_sd' => '14.1', 'plus_two_sd' => '15.5', 'plus_three_sd' => '17.0'],
            ['length_cm' => '92.0', 'minus_three_sd' => '10.1', 'minus_two_sd' => '10.9', 'minus_one_sd' => '11.9', 'median' => '13.0', 'plus_one_sd' => '14.2', 'plus_two_sd' => '15.6', 'plus_three_sd' => '17.2'],
            ['length_cm' => '92.5', 'minus_three_sd' => '10.1', 'minus_two_sd' => '11.0', 'minus_one_sd' => '12.0', 'median' => '13.1', 'plus_one_sd' => '14.3', 'plus_two_sd' => '15.8', 'plus_three_sd' => '17.4'],
            ['length_cm' => '93.0', 'minus_three_sd' => '10.2', 'minus_two_sd' => '11.1', 'minus_one_sd' => '12.1', 'median' => '13.2', 'plus_one_sd' => '14.5', 'plus_two_sd' => '15.9', 'plus_three_sd' => '17.5'],
            ['length_cm' => '93.5', 'minus_three_sd' => '10.3', 'minus_two_sd' => '11.2', 'minus_one_sd' => '12.2', 'median' => '13.3', 'plus_one_sd' => '14.6', 'plus_two_sd' => '16.1', 'plus_three_sd' => '17.7'],
            ['length_cm' => '94.0', 'minus_three_sd' => '10.4', 'minus_two_sd' => '11.3', 'minus_one_sd' => '12.3', 'median' => '13.5', 'plus_one_sd' => '14.7', 'plus_two_sd' => '16.2', 'plus_three_sd' => '17.9'],
            ['length_cm' => '94.5', 'minus_three_sd' => '10.5', 'minus_two_sd' => '11.4', 'minus_one_sd' => '12.4', 'median' => '13.6', 'plus_one_sd' => '14.9', 'plus_two_sd' => '16.4', 'plus_three_sd' => '18.0'],
            ['length_cm' => '95.0', 'minus_three_sd' => '10.6', 'minus_two_sd' => '11.5', 'minus_one_sd' => '12.6', 'median' => '13.7', 'plus_one_sd' => '15.0', 'plus_two_sd' => '16.5', 'plus_three_sd' => '18.2'],
            ['length_cm' => '95.5', 'minus_three_sd' => '10.7', 'minus_two_sd' => '11.6', 'minus_one_sd' => '12.7', 'median' => '13.8', 'plus_one_sd' => '15.2', 'plus_two_sd' => '16.7', 'plus_three_sd' => '18.4'],
            ['length_cm' => '96.0', 'minus_three_sd' => '10.8', 'minus_two_sd' => '11.7', 'minus_one_sd' => '12.8', 'median' => '14.0', 'plus_one_sd' => '15.3', 'plus_two_sd' => '16.8', 'plus_three_sd' => '18.6'],
            ['length_cm' => '96.5', 'minus_three_sd' => '10.9', 'minus_two_sd' => '11.8', 'minus_one_sd' => '12.9', 'median' => '14.1', 'plus_one_sd' => '15.4', 'plus_two_sd' => '17.0', 'plus_three_sd' => '18.7'],
            ['length_cm' => '97.0', 'minus_three_sd' => '11.0', 'minus_two_sd' => '12.0', 'minus_one_sd' => '13.0', 'median' => '14.2', 'plus_one_sd' => '15.6', 'plus_two_sd' => '17.1', 'plus_three_sd' => '18.9'],
            ['length_cm' => '97.5', 'minus_three_sd' => '11.1', 'minus_two_sd' => '12.1', 'minus_one_sd' => '13.1', 'median' => '14.4', 'plus_one_sd' => '15.7', 'plus_two_sd' => '17.3', 'plus_three_sd' => '19.1'],
            ['length_cm' => '98.0', 'minus_three_sd' => '11.2', 'minus_two_sd' => '12.2', 'minus_one_sd' => '13.3', 'median' => '14.5', 'plus_one_sd' => '15.9', 'plus_two_sd' => '17.5', 'plus_three_sd' => '19.3'],
            ['length_cm' => '98.5', 'minus_three_sd' => '11.3', 'minus_two_sd' => '12.3', 'minus_one_sd' => '13.4', 'median' => '14.6', 'plus_one_sd' => '16.0', 'plus_two_sd' => '17.6', 'plus_three_sd' => '19.5'],
            ['length_cm' => '99.0', 'minus_three_sd' => '11.4', 'minus_two_sd' => '12.4', 'minus_one_sd' => '13.5', 'median' => '14.8', 'plus_one_sd' => '16.2', 'plus_two_sd' => '17.8', 'plus_three_sd' => '19.6'],
            ['length_cm' => '99.5', 'minus_three_sd' => '11.5', 'minus_two_sd' => '12.5', 'minus_one_sd' => '13.6', 'median' => '14.9', 'plus_one_sd' => '16.3', 'plus_two_sd' => '18.0', 'plus_three_sd' => '19.8'],
            ['length_cm' => '100.0', 'minus_three_sd' => '11.6', 'minus_two_sd' => '12.6', 'minus_one_sd' => '13.7', 'median' => '15.0', 'plus_one_sd' => '16.5', 'plus_two_sd' => '18.1', 'plus_three_sd' => '20.0'],
            ['length_cm' => '100.5', 'minus_three_sd' => '11.7', 'minus_two_sd' => '12.7', 'minus_one_sd' => '13.9', 'median' => '15.2', 'plus_one_sd' => '16.6', 'plus_two_sd' => '18.3', 'plus_three_sd' => '20.2'],
            ['length_cm' => '101.0', 'minus_three_sd' => '11.8', 'minus_two_sd' => '12.8', 'minus_one_sd' => '14.0', 'median' => '15.3', 'plus_one_sd' => '16.8', 'plus_two_sd' => '18.5', 'plus_three_sd' => '20.4'],
            ['length_cm' => '101.5', 'minus_three_sd' => '11.9', 'minus_two_sd' => '13.0', 'minus_one_sd' => '14.1', 'median' => '15.5', 'plus_one_sd' => '17.0', 'plus_two_sd' => '18.7', 'plus_three_sd' => '20.6'],
            ['length_cm' => '102.0', 'minus_three_sd' => '12.0', 'minus_two_sd' => '13.1', 'minus_one_sd' => '14.3', 'median' => '15.6', 'plus_one_sd' => '17.1', 'plus_two_sd' => '18.9', 'plus_three_sd' => '20.8'],
            ['length_cm' => '102.5', 'minus_three_sd' => '12.1', 'minus_two_sd' => '13.2', 'minus_one_sd' => '14.4', 'median' => '15.8', 'plus_one_sd' => '17.3', 'plus_two_sd' => '19.0', 'plus_three_sd' => '21.0'],
            ['length_cm' => '103.0', 'minus_three_sd' => '12.3', 'minus_two_sd' => '13.3', 'minus_one_sd' => '14.5', 'median' => '15.9', 'plus_one_sd' => '17.5', 'plus_two_sd' => '19.2', 'plus_three_sd' => '21.3'],
            ['length_cm' => '103.5', 'minus_three_sd' => '12.4', 'minus_two_sd' => '13.5', 'minus_one_sd' => '14.7', 'median' => '16.1', 'plus_one_sd' => '17.6', 'plus_two_sd' => '19.4', 'plus_three_sd' => '21.5'],
            ['length_cm' => '104.0', 'minus_three_sd' => '12.5', 'minus_two_sd' => '13.6', 'minus_one_sd' => '14.8', 'median' => '16.2', 'plus_one_sd' => '17.8', 'plus_two_sd' => '19.6', 'plus_three_sd' => '21.7'],
            ['length_cm' => '104.5', 'minus_three_sd' => '12.6', 'minus_two_sd' => '13.7', 'minus_one_sd' => '15.0', 'median' => '16.4', 'plus_one_sd' => '18.0', 'plus_two_sd' => '19.8', 'plus_three_sd' => '21.9'],
            ['length_cm' => '105.0', 'minus_three_sd' => '12.7', 'minus_two_sd' => '13.8', 'minus_one_sd' => '15.1', 'median' => '16.5', 'plus_one_sd' => '18.2', 'plus_two_sd' => '20.0', 'plus_three_sd' => '22.2'],
            ['length_cm' => '105.5', 'minus_three_sd' => '12.8', 'minus_two_sd' => '14.0', 'minus_one_sd' => '15.3', 'median' => '16.7', 'plus_one_sd' => '18.4', 'plus_two_sd' => '20.2', 'plus_three_sd' => '22.4'],
            ['length_cm' => '106.0', 'minus_three_sd' => '13.0', 'minus_two_sd' => '14.1', 'minus_one_sd' => '15.4', 'median' => '16.9', 'plus_one_sd' => '18.5', 'plus_two_sd' => '20.5', 'plus_three_sd' => '22.6'],
            ['length_cm' => '106.5', 'minus_three_sd' => '13.1', 'minus_two_sd' => '14.3', 'minus_one_sd' => '15.6', 'median' => '17.1', 'plus_one_sd' => '18.7', 'plus_two_sd' => '20.7', 'plus_three_sd' => '22.9'],
            ['length_cm' => '107.0', 'minus_three_sd' => '13.2', 'minus_two_sd' => '14.4', 'minus_one_sd' => '15.7', 'median' => '17.2', 'plus_one_sd' => '18.9', 'plus_two_sd' => '20.9', 'plus_three_sd' => '23.1'],
            ['length_cm' => '107.5', 'minus_three_sd' => '13.3', 'minus_two_sd' => '14.5', 'minus_one_sd' => '15.9', 'median' => '17.4', 'plus_one_sd' => '19.1', 'plus_two_sd' => '21.1', 'plus_three_sd' => '23.4'],
            ['length_cm' => '108.0', 'minus_three_sd' => '13.5', 'minus_two_sd' => '14.7', 'minus_one_sd' => '16.0', 'median' => '17.6', 'plus_one_sd' => '19.3', 'plus_two_sd' => '21.3', 'plus_three_sd' => '23.6'],
            ['length_cm' => '108.5', 'minus_three_sd' => '13.6', 'minus_two_sd' => '14.8', 'minus_one_sd' => '16.2', 'median' => '17.8', 'plus_one_sd' => '19.5', 'plus_two_sd' => '21.6', 'plus_three_sd' => '23.9'],
            ['length_cm' => '109.0', 'minus_three_sd' => '13.7', 'minus_two_sd' => '15.0', 'minus_one_sd' => '16.4', 'median' => '18.0', 'plus_one_sd' => '19.7', 'plus_two_sd' => '21.8', 'plus_three_sd' => '24.2'],
            ['length_cm' => '109.5', 'minus_three_sd' => '13.9', 'minus_two_sd' => '15.1', 'minus_one_sd' => '16.5', 'median' => '18.1', 'plus_one_sd' => '20.0', 'plus_two_sd' => '22.0', 'plus_three_sd' => '24.4'],
            ['length_cm' => '110.0', 'minus_three_sd' => '14.0', 'minus_two_sd' => '15.3', 'minus_one_sd' => '16.7', 'median' => '18.3', 'plus_one_sd' => '20.2', 'plus_two_sd' => '22.3', 'plus_three_sd' => '24.7'],
        ]);
    }
}

// php artisan make:seeder UserSeeder = buaat seeder
// php artisan db:seed --class=RuleSeeder = migrate data to db
